[project]

site_name = "XNAT CLI for BIDS"
site_description = "A command-line interface for logging into an XNAT server, querying experiments and downloading files, then converting to the BIDS standard format."
site_author = "NIMH Data Science and Sharing Team"
site_url = "https://xnatbidscli.readthedocs.io/"
repo_url = "https://github.com/nimh-dsst/xnat-bids-cli"
repo_name = "nimh-dsst/xnat-bids-cli"
edit_uri = "edit/main/docs/"

copyright = """
Copyright &copy; 2026 NIMH Data Science and Sharing Team
"""

nav = [
  { "Overview" = "index.md" },
  { "Installation" = "installation.md" },
  { "Quick Start" = "quickstart.md" },
  { "Manual Steps" = "manual.md" },
  { "Frequently Asked Questions" = "faq.md" },
  { "Using Excel" = "excel.md" },
  { "Design" = "design.md" },
  { "CLI Reference" = [
      { "xnatbidscli login" = "cli/login.md" },
      { "xnatbidscli query" = "cli/query.md" },
      { "xnatbidscli download" = "cli/download.md" },
      { "xnatbidscli mriconfig" = "cli/mriconfig.md" },
      { "xnatbidscli mriconvert" = "cli/mriconvert.md" },
      { "xnatbidscli physioconvert" = "cli/physioconvert.md" },
      { "xnatbidscli bidsmap" = "cli/bidsmap.md" },
      { "xnatbidscli cubids" = "cli/cubids.md" },
    ] },
]

extra_javascript = [
  "assets/js/faq.js",
]

[project.theme]

logo = "assets/images/logo.png"
favicon = "assets/images/favicon.png"

language = "en"

features = [
    "content.code.annotate",
    "content.code.copy",
    "navigation.footer",
    "navigation.indexes",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/nimh-dsst/xnat-bids-cli"
